@startuml
allowmixing
skinparam handwritten true
skinparam roundcorner 20
skinparam monochrome true
skinparam arrowThickness 2
skinparam BoxPadding 60

' hide the spot
hide circle

entity "SFU Controller" as sfu-controller {
    * sfu-monitor
    --
    ...
}

() "Observer" as observer
() "SFU" as sfu

"sfu-controller" -r-> observer : Samples


sfu <-u-> "sfu-controller"

@enduml
