[[main]]
name = "Docs"
url = "/docs/overview/introduction/"
weight = 10
[[main]]
name = "Live example ↗"
url = "https://webrtc-observer.org/"
weight = 20
[[main]]
name = "Contact"
url = "/contact/"
weight = 30
[[social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path></svg>'
url = "https://github.com/observertc"
weight = 10

[[docs]]
name = "Start here"
weight = 10
identifier = "overview"
url = "/docs/overview/"

[[sidebar_docs]]
name = "Start here"
weight = 10
pageRef = "/docs/overview"

[[docs]]
name = "Client Monitor"
weight = 20
identifier = "client-monitor-js"
url = "/docs/client-monitor-js/"

[[sidebar_docs]]
name = "Client Monitor"
weight = 20
pageRef = "/docs/client-monitor-js"

[[docs]]
name = "Observer"
weight = 30
identifier = "observer-js"
url = "/docs/observer-js/"

[[sidebar_docs]]
name = "Observer"
weight = 30
pageRef = "/docs/observer-js"

[[docs]]
name = "Protobuf Codec"
weight = 40
identifier = "samples-protobuf-codec"
url = "/docs/samples-protobuf-codec/"

[[sidebar_docs]]
name = "Protobuf Codec"
weight = 40
pageRef = "/docs/samples-protobuf-codec"

[[docs]]
name = "JSON Codec"
weight = 50
identifier = "samples-json-codec"
url = "/docs/samples-json-codec/"

[[sidebar_docs]]
name = "JSON Codec"
weight = 50
pageRef = "/docs/samples-json-codec"

[[docs]]
name = "Implementation reference"
weight = 60
identifier = "reference"
url = "/docs/reference/"

[[sidebar_docs]]
name = "Implementation reference"
weight = 60
pageRef = "/docs/reference"

[[docs]]
name = "Schema"
weight = 70
identifier = "schema"
url = "/docs/schema/"

[[sidebar_docs]]
name = "Schema"
weight = 70
pageRef = "/docs/schema"

[[footer]]
name = "Privacy"
url = "/privacy/"
weight = 10
[[footer]]
name = "Contact"
url = "/contact/"
weight = 20
