@startuml
allowmixing
skinparam handwritten true
skinparam roundcorner 20
skinparam monochrome true
skinparam arrowThickness 2
skinparam BoxPadding 60

' hide the spot
hide circle

entity "SFU Controller" as sfu-controller {
    * sfu-monitor
    --
    ...
}

() "SFU" as sfu

entity "WebRTC App" as webrtc-app {
    * client-monitor
    --
    ...
}

() "WebRTCStats" as webrtc


"sfu-controller" <-d-> sfu
"webrtc-app" <-d-> webrtc

@enduml
