name: Fetch and publish Docker Deployment Tutorials page
on:
  repository_dispatch:
    types: [updated-docker-deployments]
jobs:
  updateSchema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          git config --global user.name "autobot"
          git config --global user.email "info@observertc.org"
          git fetch origin main
          cd scripts
          pip install -r requirements.txt
          python fetch_docker_deployments.py
          python merge_pr.py \
            -p ObserveRTC \
            -r website-3.0 \
            -t ${{ secrets.PAT }} \
            -b autobot/update-docker-deployments \
            -cm "update docker deployment changes" \
            -ti "Autobot/Docker Deployment Changes" \
            -bm "Automatic docker deployment changes"
